import type { Account, Resource, Execution, Discovery } from "./types";
export const demoAccounts: Account[] = [
  {
    id: "demo-studio-prod",
    name: "Studio Production",
    profile: "work",
    workspace: "Studio",
    color: "#b8c8ad",
  },
  {
    id: "demo-studio-dev",
    name: "Studio Development",
    profile: "work",
    workspace: "Studio",
    color: "#b4b4d5",
  },
  {
    id: "demo-personal",
    name: "Personal",
    profile: "personal",
    workspace: "Personal",
    color: "#dbb995",
  },
];
export const demoResources: Resource[] = [
  {
    id: "container-demo",
    name: "image-processor",
    kind: "Containers",
    status: "Available",
    description: "Image processing application",
    modified: "2026-10-01T01:00:00Z",
    metadata: {
      configuration: { image: "registry.example.com/image-processor:latest" },
    },
  },
  {
    id: "durable-demo",
    name: "SessionStore",
    kind: "Durable Objects",
    status: "Available",
    description: "Session state",
    modified: "",
    metadata: { class: "SessionStore", script: "studio-api" },
  },
  {
    id: "workflow-demo",
    name: "daily-report",
    kind: "Workflows",
    status: "Available",
    description: "Daily reporting workflow",
    modified: "2026-10-01T01:00:00Z",
    metadata: { class_name: "DailyReport", script_name: "studio-api" },
  },
  {
    id: "dispatch-demo",
    name: "customer-workers",
    kind: "Workers for Platforms",
    status: "Available",
    description: "Customer dispatch namespace",
    modified: "2026-10-01T01:00:00Z",
    metadata: {
      namespace_id: "dispatch-demo",
      namespace_name: "customer-workers",
    },
  },
  {
    id: "pages:demo-site",
    name: "studio-site",
    kind: "Workers",
    product: "Pages",
    status: "Available",
    description: "Marketing website",
    modified: "2026-10-01T01:00:00Z",
  },
  {
    id: "w1",
    name: "studio-api",
    kind: "Workers",
    status: "Deployed",
    description: "The API at the heart of Studio",
    modified: "12 minutes ago",
    metadata: {
      environment: "Production",
      runtime: "Cloudflare Workers",
      compatibility_date: "2026-09-28",
      deployment: "a1b9e82",
      bindings: ["DB → studio-db", "CACHE → app-cache"],
    },
  },
  {
    id: "w2",
    name: "edge-router",
    kind: "Workers",
    status: "Deployed",
    description: "Request routing & middleware",
    modified: "2 hours ago",
    metadata: {
      environment: "Production",
      deployment: "f49c210",
      bindings: ["CONFIG → app-config"],
    },
  },
  {
    id: "w3",
    name: "scheduled-checks",
    kind: "Workers",
    status: "Deployed",
    description: "Uptime monitoring, around the clock",
    modified: "Yesterday",
    metadata: { environment: "Production", deployment: "e861df0" },
  },
  {
    id: "w4",
    name: "image-proxy",
    kind: "Workers",
    status: "Deployed",
    description: "Image optimization at the edge",
    modified: "2 days ago",
    metadata: { environment: "Production" },
  },
  {
    id: "z1",
    name: "example.com",
    kind: "Zones",
    status: "Active",
    description: "Business plan · Full setup",
    modified: "24 minutes ago",
    metadata: {
      plan: "Business",
      nameservers: ["ada.ns.cloudflare.com", "ned.ns.cloudflare.com"],
    },
  },
  {
    id: "z2",
    name: "example.net",
    kind: "Zones",
    status: "Active",
    description: "Pro plan · Full setup",
    modified: "Yesterday",
    metadata: { plan: "Pro" },
  },
  {
    id: "z3",
    name: "example.org",
    kind: "Zones",
    status: "Active",
    description: "Free plan · Full setup",
    modified: "3 days ago",
    metadata: { plan: "Free" },
  },
  {
    id: "dns1",
    name: "example.com",
    kind: "DNS",
    type: "A",
    content: "192.0.2.1",
    proxied: true,
    ttl: 1,
    zoneId: "z1",
    status: "Proxied",
    description: "Root domain",
    modified: "24 minutes ago",
  },
  {
    id: "dns2",
    name: "api.example.com",
    kind: "DNS",
    type: "CNAME",
    content: "studio-api.workers.dev",
    proxied: true,
    ttl: 1,
    zoneId: "z1",
    status: "Proxied",
    description: "API endpoint",
    modified: "Yesterday",
  },
  {
    id: "dns3",
    name: "www.example.com",
    kind: "DNS",
    type: "CNAME",
    content: "example.com",
    proxied: true,
    ttl: 1,
    zoneId: "z1",
    status: "Proxied",
    description: "Website alias",
    modified: "2 days ago",
  },
  {
    id: "dns4",
    name: "example.com",
    kind: "DNS",
    type: "MX",
    content: "mx1.example.net",
    proxied: false,
    ttl: 3600,
    zoneId: "z1",
    status: "DNS only",
    description: "Email routing",
    modified: "5 days ago",
    metadata: { priority: 10 },
  },
  {
    id: "dns5",
    name: "_dmarc.example.com",
    kind: "DNS",
    type: "TXT",
    content: "v=DMARC1; p=reject;",
    proxied: false,
    ttl: 3600,
    zoneId: "z1",
    status: "DNS only",
    description: "Email policy",
    modified: "5 days ago",
  },
  {
    id: "db1",
    name: "studio-db",
    kind: "D1",
    status: "Available",
    description: "Primary application database",
    modified: "38 minutes ago",
    metadata: { size: "24.8 MB", tables: 12, region: "Western Europe" },
  },
  {
    id: "db2",
    name: "analytics-db",
    kind: "D1",
    status: "Available",
    description: "Events & uptime history",
    modified: "3 hours ago",
    metadata: { size: "108.2 MB", tables: 6, region: "Western Europe" },
  },
  {
    id: "b1",
    name: "studio-assets",
    kind: "R2",
    status: "Available",
    description: "Public assets & media",
    modified: "1 hour ago",
    metadata: { location: "Western Europe", storage: "Standard" },
  },
  {
    id: "b2",
    name: "database-backups",
    kind: "R2",
    status: "Available",
    description: "Daily database snapshots",
    modified: "6 hours ago",
    metadata: { location: "Western Europe", storage: "Standard" },
  },
  {
    id: "b3",
    name: "user-uploads",
    kind: "R2",
    status: "Available",
    description: "Workspace attachments",
    modified: "Yesterday",
    metadata: { location: "Western Europe", storage: "Standard" },
  },
  {
    id: "kv1",
    name: "app-cache",
    kind: "KV",
    status: "Available",
    description: "Response cache",
    modified: "2 hours ago",
  },
  {
    id: "kv2",
    name: "app-config",
    kind: "KV",
    status: "Available",
    description: "Shared configuration",
    modified: "Yesterday",
  },
  {
    id: "q1",
    name: "notification-queue",
    kind: "Queues",
    status: "Available",
    description: "Email & webhook delivery",
    modified: "3 hours ago",
  },
];
export const demoCommands: Discovery[] = [
  {
    command: "cf containers applications list",
    fullPath: ["containers", "applications", "list"],
    description: "List container applications",
  },
  {
    command: "cf durable-objects namespaces list",
    fullPath: ["durable-objects", "namespaces", "list"],
    description: "List Durable Object namespaces",
  },
  {
    command: "cf workflows list",
    fullPath: ["workflows", "list"],
    description: "List workflows",
  },
  {
    command: "cf workers-for-platforms dispatch-namespaces list",
    fullPath: ["workers-for-platforms", "dispatch-namespaces", "list"],
    description: "List Workers for Platforms dispatch namespaces",
  },
  {
    command: "cf workers list",
    fullPath: ["workers", "list"],
    description: "List Workers in the selected account.",
  },
  {
    command: "cf dns records create",
    fullPath: ["dns", "records", "create"],
    description: "Create a DNS record in a zone.",
  },
  {
    command: "cf dns records list",
    fullPath: ["dns", "records", "list"],
    description: "List and search DNS records.",
  },
  {
    command: "cf r2 buckets create",
    fullPath: ["r2", "buckets", "create"],
    description: "Create an R2 storage bucket.",
  },
  {
    command: "cf d1 create",
    fullPath: ["d1", "create"],
    description: "Create a D1 database.",
  },
  {
    command: "cf zones purge-cache",
    fullPath: ["zones", "purge-cache"],
    description: "Purge cached content for a zone.",
  },
  {
    command: "cf zones list",
    fullPath: ["zones", "list"],
    description: "List zones in your account.",
  },
];
export const demoHistory: Execution[] = [
  ["workers list", "12 minutes ago", 348],
  ["dns records list", "24 minutes ago", 216],
  ["d1 list", "38 minutes ago", 192],
].map(([command, , duration], i) => ({
  id: "demo-job-" + i,
  success: true,
  data: { result: [], demo: true },
  rawStdout: '{ "success": true, "demo": true }',
  rawStderr: "",
  exitCode: 0,
  durationMs: Number(duration),
  command: `cf ${command} --profile work --account-id demo-studio-prod`,
  profile: "work",
  accountId: "demo-studio-prod",
  startedAt: new Date(Date.now() - (i + 1) * 720000).toISOString(),
  finishedAt: new Date(Date.now() - (i + 1) * 720000).toISOString(),
}));
